# Generated by Django 5.2.13 on 2026-05-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('safe', 'Seguro (0-30)'), ('warning', 'Sospechoso (31-60)'), ('danger', 'Alto riesgo (61-80)'), ('malware', 'Malware (81-100)')], default='safe', max_length=10)),
                ('threat_name', models.CharField(blank=True, max_length=200)),
                ('blocked', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('executable', 'Ejecutable'), ('office', 'Documento Office'), ('pdf', 'PDF'), ('archive', 'Archivo comprimido'), ('script', 'Script'), ('body', 'Cuerpo del correo'), ('url', 'URL'), ('aggregate', 'Agregado'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('real_mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('extension_spoof', models.BooleanField(default=False)),
                ('yara_matches', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('iocs', models.JSONField(blank=True, default=dict)),
                ('analyzers_run', models.JSONField(blank=True, default=list)),
                ('body_score', models.IntegerField(default=0)),
                ('body_evidence', models.JSONField(blank=True, default=list)),
                ('body_threat', models.CharField(blank=True, max_length=200)),
                ('attachments_reports', models.JSONField(blank=True, default=list)),
                ('ai_verdict', models.CharField(blank=True, max_length=20)),
                ('ai_threat_type', models.CharField(blank=True, max_length=100)),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='mail.emailmessage')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
