# Generated by Django 5.2.13 on 2026-05-30 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aliases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='aliases.alias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('body_html_raw', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('has_attachment', models.BooleanField(default=False)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('risk_score', models.IntegerField(default=0)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='aliases.alias')),
            ],
            options={
                'verbose_name': 'Correo recibido',
                'verbose_name_plural': 'Correos recibidos',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=2500)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('attachments_count', models.IntegerField(default=0)),
                ('attachments_meta', models.JSONField(blank=True, default=list)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='aliases.alias')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
